export type PublicMenuLanguage = 'ar' | 'fr' | 'en'

interface StatusMessages { pending:string; accepted:string; preparing:string; ready:string; served:string }
export interface PublicMenuTexts {
	cart:string; total:string; orderNow:string; empty:string; addToCart:string; quantity:string; remove:string; dzd:string; categories:string; products:string; loading:string; table:string; order:string; myOrders:string; orderStatus:string; pending:string; accepted:string; preparing:string; ready:string; served:string; orderNote:string; addNote:string; orderHistory:string; noOrders:string; orderPlaced:string; orderUpdated:string; systemInactive:string; systemInactiveMessage:string; notifications:string; enableSounds:string; items:string; viewProducts:string; unavailable:string; orderItems:string; orderReady:string; backToCategories:string; searchPlaceholder:string; add:string; retry:string; noProducts:string; noCategories:string; restaurant:string; toggleLanguage:string; orderTracker:string; openCart:string; increase:string; decrease:string; enableAudio:string; disableAudio:string; statusMessages:StatusMessages
}

const texts: Record<PublicMenuLanguage, PublicMenuTexts> = {
	ar: {
		cart: 'السلة', total: 'المجموع', orderNow: 'اطلب الآن', empty: 'فارغ', addToCart: 'إضافة للسلة', quantity: 'الكمية', remove: 'حذف', dzd: 'د.ج', categories: 'الفئات', products: 'المنتجات', loading: 'جاري التحميل...', table: 'طاولة', order: 'طلب', myOrders: 'طلباتي', orderStatus: 'حالة الطلب', pending: 'قيد الانتظار', accepted: 'مقبول', preparing: 'قيد التحضير', ready: 'جاهز', served: 'تم التقديم', orderNote: 'ملاحظة الطلب', addNote: 'إضافة ملاحظة', orderHistory: 'تاريخ الطلبات', noOrders: 'لا توجد طلبات', orderPlaced: 'تم تقديم الطلب', orderUpdated: 'تم تحديث الطلب', systemInactive: 'النظام غير نشط', systemInactiveMessage: 'النظام مغلق حالياً. يرجى المحاولة لاحقاً.', notifications: 'الإشعارات', enableSounds: 'تفعيل الأصوات', items: 'عناصر', viewProducts: 'عرض المنتجات', unavailable: 'غير متوفر', orderItems: 'عناصر الطلب', orderReady: 'طلبكم جاهز!', backToCategories: 'العودة للفئات', searchPlaceholder: 'بحث...', add: 'إضافة', retry:'إعادة المحاولة', noProducts:'لا توجد منتجات', noCategories:'لا توجد فئات', restaurant:'مطعم', toggleLanguage:'تغيير اللغة', orderTracker:'تتبع الطلب', openCart:'فتح السلة', increase:'زيادة', decrease:'إنقاص', enableAudio:'تفعيل الصوت', disableAudio:'إيقاف الصوت', statusMessages: { pending: 'طلبكم قيد المراجعة', accepted: 'تم قبول الطلب وبدء التحضير', preparing: 'يتم تحضير طلبكم الآن', ready: 'طلبكم جاهز للاستلام', served: 'تم تقديم طلبكم. شهية طيبة' }
	},
	fr: {
		cart: 'Panier', total: 'Total', orderNow: 'Commander', empty: 'Vide', addToCart: 'Ajouter au panier', quantity: 'Quantité', remove: 'Supprimer', dzd: 'DA', categories: 'Catégories', products: 'Produits', loading: 'Chargement...', table: 'Table', order: 'Commande', myOrders: 'Mes commandes', orderStatus: 'Statut de la commande', pending: 'En attente', accepted: 'Acceptée', preparing: 'En préparation', ready: 'Prête', served: 'Servie', orderNote: 'Note de commande', addNote: 'Ajouter une note', orderHistory: 'Historique des commandes', noOrders: 'Aucune commande', orderPlaced: 'Commande passée', orderUpdated: 'Commande mise à jour', systemInactive: 'Système inactif', systemInactiveMessage: 'Le système est actuellement fermé. Veuillez réessayer plus tard.', notifications: 'Notifications', enableSounds: 'Activer les sons', items: 'articles', viewProducts: 'Voir les produits', unavailable: 'Indisponible', orderItems: 'Articles de commande', orderReady: 'Votre commande est prête!', backToCategories: 'Retour aux catégories', searchPlaceholder: 'Rechercher...', add: 'Ajouter', retry:'Réessayer', noProducts:'Aucun produit', noCategories:'Aucune catégorie', restaurant:'Restaurant', toggleLanguage:'Changer la langue', orderTracker:'Suivi commande', openCart:'Ouvrir le panier', increase:'Augmenter', decrease:'Diminuer', enableAudio:'Activer le son', disableAudio:'Désactiver le son', statusMessages: { pending: 'Votre commande est en cours de révision', accepted: 'Commande acceptée et préparation commencée', preparing: 'Votre commande est en cours de préparation', ready: 'Votre commande est prête à être récupérée', served: 'Votre commande a été servie. Bon appétit' }
	},
	en: {
		cart: 'Cart', total: 'Total', orderNow: 'Order now', empty: 'Empty', addToCart: 'Add to cart', quantity: 'Quantity', remove: 'Remove', dzd: 'DZD', categories: 'Categories', products: 'Products', loading: 'Loading...', table: 'Table', order: 'Order', myOrders: 'My Orders', orderStatus: 'Order Status', pending: 'Pending', accepted: 'Accepted', preparing: 'Preparing', ready: 'Ready', served: 'Served', orderNote: 'Order note', addNote: 'Add note', orderHistory: 'Order history', noOrders: 'No orders', orderPlaced: 'Order placed', orderUpdated: 'Order updated', systemInactive: 'System inactive', systemInactiveMessage: 'The system is currently closed. Please try again later.', notifications: 'Notifications', enableSounds: 'Enable sounds', items: 'items', viewProducts: 'View products', unavailable: 'Unavailable', orderItems: 'Order items', orderReady: 'Your order is ready!', backToCategories: 'Back to categories', searchPlaceholder: 'Search...', add: 'Add', retry:'Retry', noProducts:'No products found', noCategories:'No categories found', restaurant:'Restaurant', toggleLanguage:'Toggle language', orderTracker:'Order tracker', openCart:'Open cart', increase:'Increase', decrease:'Decrease', enableAudio:'Enable sound', disableAudio:'Disable sound', statusMessages: { pending: 'Your order is under review', accepted: 'Order accepted, preparation started', preparing: 'Your order is being prepared', ready: 'Your order is ready to pick up', served: 'Your order has been served. Enjoy' }
	}
}

export function getPublicMenuTexts(lang: PublicMenuLanguage): PublicMenuTexts { return texts[lang] || texts.en }
